#!/bin/sh

if [ ! -x $GOPATH/bin/dep ]; then
  go get -u github.com/golang/dep/cmd/dep
fi

export PATH=$GOPATH/bin:$PATH
if [ ! -x vendor ]; then
  dep ensure
fi

prgm=$1
shift;
bash -i -c "$prgm $@"
