#!/bin/bash

if [ ! -x $NVM_DIR/nvm.sh ]; then
  bash -i -c "wget -O - https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash"
fi
# make sure we comment out the nvm bash_completion line because it doesn't work.
sed -i 's/.*NVM_DIR\/bash_completion/#&/' $HOME/.bashrc

bash -i -c "nvm install $NODE_VERSION && nvm alias default && nvm use default"

if [ ! -x node_modules/.bin/deps-ok ]; then
  npm install deps-ok
fi

./node_modules/.bin/deps-ok &> /dev/null
if [ $? -ne 0 ]; then
  npm install --quiet
fi

npm run test-selenium-install
