package mocks

import mailer "github.com/18F/cg-dashboard/mailer"
import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields:
// emailAddress, subject, html, text.
func (_m *Mailer) SendEmail(emailAddress string, subject string, html, text []byte) error {
	ret := _m.Called(emailAddress, subject, html, text)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte, []byte) error); ok {
		r0 = rf(emailAddress, subject, html, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ mailer.Mailer = (*Mailer)(nil)
