package mocks

import mailer "github.com/18F/cg-dashboard/mailer"
import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendInviteEmail provides a mock function with given fields: emailAddress, URL
func (_m *Mailer) SendInviteEmail(emailAddress string, URL string) error {
	ret := _m.Called(emailAddress, URL)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(emailAddress, URL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ mailer.Mailer = (*Mailer)(nil)
